### ISSUE TITLE
Compose

### ISSUE THREAD

**Issue by djryan012** [CCOSTAN/Docker_Support#2]
Since I am having issue with my pi and sd cards I thinks its time to switch HA to my Ubuntu 18 Server. Do you have a more update example of your compose file.

**Comment by CCOSTAN** [comment]
Here is the one I am using now. 
https://github.com/CCOSTAN/Docker_Support/commit/25aad81b8d10d36cbff0ffcf7dd73aa0d6d3c6f1

and a small write up of the containers. 
https://www.vcloudinfo.com/2018/06/rolling-out-some-new-docker-containers.html

<blockquote><img src="https://www.vcloudinfo.com/wp-content/uploads/2019/01/vCloud@4x.png" width="48" align="right"><div><img src="https://www.vcloudinfo.com/wp-content/uploads/2019/01/favicon.png" height="14"> vCloudInfo</div><div><strong><a href="https://www.vcloudinfo.com/2018/06/rolling-out-some-new-docker-containers.html">Rolling Out Some New Docker Containers To My Smart Home. | VCloudInfo</a></strong></div><div>I thought I would write up some new changes I have made to the house related to my Docker setup.  Recently, I’ve added some really neat new containers to</div></blockquote>
